import {
  getViewer,
  loginWithCredentials,
  signupWithCredentials,
} from "@/lib/server/auth";
import {
  createApplication,
  createManualApplication,
  createManualPosting,
  createResume,
  deleteCoverLetterItem,
  getAllPostingsPage,
  getApplication,
  getApplicationCoverLetterItems,
  getApplications,
  getBookmarkedPostingsPage,
  getCalendarMonth,
  getCoverLetterLibraryPage,
  getDashboard,
  getIgnoredPostingsPage,
  getInterestingPostingsPage,
  getNewPostingsPage,
  getPostingOverview,
  getPostings,
  getResumes,
  getSourceCrawlInfo,
  getSourceSyncRuns,
  getSources,
  getTodoPostingsPage,
  patchApplication,
  patchCoverLetterItem,
  patchPosting,
  patchResume,
  postCoverLetterItem,
  postSourceCrawlInfo,
  postSyncSource,
} from "@/lib/server/data";

const CACHE_TAGS = {
  applications: "applications",
  coverLetter: "cover-letter",
  dashboard: "dashboard",
  postings: "postings",
  resumes: "resumes",
  sourceCrawlInfo: "source-crawl-info",
  sources: "sources",
} as const;

export { CACHE_TAGS };
export {
  createApplication,
  createManualApplication,
  createManualPosting,
  createResume,
  deleteCoverLetterItem,
  getAllPostingsPage,
  getApplication,
  getApplicationCoverLetterItems,
  getApplications,
  getBookmarkedPostingsPage,
  getCalendarMonth,
  getCoverLetterLibraryPage,
  getDashboard,
  getIgnoredPostingsPage,
  getInterestingPostingsPage,
  getNewPostingsPage,
  getPostingOverview,
  getPostings,
  getResumes,
  getSourceCrawlInfo,
  getSourceSyncRuns,
  getSources,
  getTodoPostingsPage,
  getViewer,
  loginWithCredentials,
  patchApplication,
  patchCoverLetterItem,
  patchPosting,
  patchResume,
  postCoverLetterItem,
  postSourceCrawlInfo,
  postSyncSource,
  signupWithCredentials,
};
