import "server-only";

import { cache } from "react";
import type { User as SupabaseUser } from "@supabase/supabase-js";

import type { Viewer } from "@/lib/types";
import { type DbExecutor, sql } from "@/lib/db";
import { createClient as createSupabaseServerClient } from "@/utils/supabase/server";
import { getSiteUrl } from "@/utils/supabase/env";

const USERNAME_PATTERN = /^[a-zA-Z0-9][a-zA-Z0-9._-]{2,31}$/;

type AppUserRow = {
  created_at: Date | string;
  email: string | null;
  id: number;
  is_active: boolean;
  last_login_at: Date | string | null;
  role: string;
  supabase_auth_user_id: string | null;
  username: string;
};

let ensuredAuthSchema = false;

function asIsoDateTime(value: Date | string | null | undefined) {
  if (!value) {
    return null;
  }
  return value instanceof Date ? value.toISOString() : String(value);
}

function normalizeUsername(value: string) {
  return value.trim().toLowerCase();
}

function normalizeEmail(value: string) {
  return value.trim().toLowerCase();
}

function translateAuthMessage(message: string | undefined, fallback: string) {
  const normalized = message?.trim();
  if (!normalized) {
    return fallback;
  }

  if (/email not confirmed/i.test(normalized)) {
    return "이메일 인증을 완료한 뒤 로그인해 주세요.";
  }

  if (/invalid login credentials/i.test(normalized)) {
    return "이메일 또는 비밀번호가 올바르지 않습니다.";
  }

  if (/user already registered/i.test(normalized)) {
    return "이미 가입된 이메일입니다. 로그인해 주세요.";
  }

  if (/email rate limit exceeded/i.test(normalized)) {
    return "Supabase에서 아직 가입 확인 메일을 보내고 있습니다. Supabase Dashboard에서 Auth > Providers > Email > Confirm email을 꺼 주세요.";
  }

  return normalized;
}

function validateUsername(value: string) {
  const normalized = normalizeUsername(value);
  if (!USERNAME_PATTERN.test(normalized)) {
    throw new Error(
      "Username must be 3-32 chars using letters, numbers, dot, dash, or underscore.",
    );
  }
  return normalized;
}

function inferUsername(user: SupabaseUser) {
  const metadataUsername = String(user.user_metadata.username ?? "").trim();
  if (metadataUsername) {
    return metadataUsername;
  }

  const email = String(user.email ?? "").trim();
  if (email.includes("@")) {
    return email.slice(0, email.indexOf("@"));
  }

  return `user-${user.id.slice(0, 8)}`;
}

function serializeViewer(row: AppUserRow): Viewer {
  return {
    created_at: asIsoDateTime(row.created_at) ?? new Date().toISOString(),
    id: Number(row.id),
    is_active: Boolean(row.is_active),
    last_login_at: asIsoDateTime(row.last_login_at),
    role: row.role,
    username: row.username,
  };
}

async function ensureAuthSchema() {
  if (ensuredAuthSchema) {
    return;
  }

  await sql.begin(async (tx) => {
    await tx`
      create table if not exists users (
        id integer generated by default as identity primary key,
        username varchar(80) not null unique,
        password_hash text not null default 'supabase-managed',
        role varchar(20) not null default 'member',
        is_active boolean not null default true,
        last_login_at timestamp,
        created_at timestamp not null default timezone('utc', now()),
        updated_at timestamp not null default timezone('utc', now())
      )
    `;
    await tx`alter table users add column if not exists email text`;
    await tx`alter table users add column if not exists supabase_auth_user_id uuid`;
    await tx`
      create unique index if not exists uq_users_email
      on users (email)
      where email is not null
    `;
    await tx`
      create unique index if not exists uq_users_supabase_auth_user_id
      on users (supabase_auth_user_id)
      where supabase_auth_user_id is not null
    `;
  });

  ensuredAuthSchema = true;
}

async function countUsers(tx: DbExecutor) {
  const rows = await tx<{ count: number }[]>`
    select count(*)::int as count
    from users
  `;
  return Number(rows[0]?.count ?? 0);
}

async function findUserByAuthId(tx: DbExecutor, authUserId: string) {
  const rows = await tx<AppUserRow[]>`
    select id, username, role, is_active, last_login_at, created_at, email, supabase_auth_user_id
    from users
    where supabase_auth_user_id = ${authUserId}
    limit 1
  `;
  return rows[0] ?? null;
}

async function reserveAvailableUsername(
  tx: DbExecutor,
  preferred: string,
  excludeUserId?: number,
) {
  const base = validateUsername(preferred);
  let candidate = base;
  let suffix = 2;

  for (;;) {
    const rows = excludeUserId
      ? await tx<{ id: number }[]>`
          select id
          from users
          where username = ${candidate}
            and id <> ${excludeUserId}
          limit 1
        `
      : await tx<{ id: number }[]>`
          select id
          from users
          where username = ${candidate}
          limit 1
        `;
    if (rows.length === 0) {
      return candidate;
    }

    const suffixLabel = `-${suffix}`;
    candidate = `${base.slice(0, Math.max(1, 32 - suffixLabel.length))}${suffixLabel}`;
    suffix += 1;
  }
}

async function createAppUserForAuthUser(
  authUser: SupabaseUser,
  username: string,
) {
  await ensureAuthSchema();
  const normalizedUsername = validateUsername(username);
  const normalizedEmail = authUser.email ? normalizeEmail(authUser.email) : null;

  return sql.begin(async (tx) => {
    const existingAuthUser = await findUserByAuthId(tx, authUser.id);
    if (existingAuthUser) {
      return existingAuthUser;
    }

    const usernameRows = await tx<{ id: number }[]>`
      select id
      from users
      where username = ${normalizedUsername}
      limit 1
    `;
    if (usernameRows.length > 0) {
      throw new Error("Username already exists.");
    }

    if (normalizedEmail) {
      const emailRows = await tx<{ id: number }[]>`
        select id
        from users
        where email = ${normalizedEmail}
        limit 1
      `;
      if (emailRows.length > 0) {
        throw new Error("Email already exists.");
      }
    }

    const isFirstUser = (await countUsers(tx)) === 0;
    const rows = await tx<AppUserRow[]>`
      insert into users (
        username,
        password_hash,
        role,
        is_active,
        last_login_at,
        created_at,
        updated_at,
        email,
        supabase_auth_user_id
      )
      values (
        ${normalizedUsername},
        'supabase-managed',
        ${isFirstUser ? "admin" : "member"},
        true,
        timezone('utc', now()),
        timezone('utc', now()),
        timezone('utc', now()),
        ${normalizedEmail},
        ${authUser.id}::uuid
      )
      returning id, username, role, is_active, last_login_at, created_at, email, supabase_auth_user_id
    `;
    return rows[0];
  });
}

async function ensureAppUserForAuthUser(authUser: SupabaseUser) {
  await ensureAuthSchema();

  return sql.begin(async (tx) => {
    const existing = await findUserByAuthId(tx, authUser.id);
    if (existing) {
      return existing;
    }

    const normalizedEmail = authUser.email ? normalizeEmail(authUser.email) : null;
    const fallbackUsername = await reserveAvailableUsername(tx, inferUsername(authUser));
    const isFirstUser = (await countUsers(tx)) === 0;
    const rows = await tx<AppUserRow[]>`
      insert into users (
        username,
        password_hash,
        role,
        is_active,
        last_login_at,
        created_at,
        updated_at,
        email,
        supabase_auth_user_id
      )
      values (
        ${fallbackUsername},
        'supabase-managed',
        ${isFirstUser ? "admin" : "member"},
        true,
        timezone('utc', now()),
        timezone('utc', now()),
        timezone('utc', now()),
        ${normalizedEmail},
        ${authUser.id}::uuid
      )
      returning id, username, role, is_active, last_login_at, created_at, email, supabase_auth_user_id
    `;
    return rows[0];
  });
}

async function touchAppUserLogin(authUser: SupabaseUser) {
  await ensureAuthSchema();
  const existing = await findUserByAuthId(sql, authUser.id);
  if (!existing) {
    return ensureAppUserForAuthUser(authUser);
  }

  const normalizedEmail = authUser.email ? normalizeEmail(authUser.email) : null;
  const rows = await sql<AppUserRow[]>`
    update users
    set
      email = ${normalizedEmail},
      last_login_at = timezone('utc', now()),
      updated_at = timezone('utc', now())
    where id = ${existing.id}
    returning id, username, role, is_active, last_login_at, created_at, email, supabase_auth_user_id
  `;
  return rows[0] ?? existing;
}

async function getSupabaseUser() {
  const supabase = await createSupabaseServerClient();
  const {
    data: { user },
    error,
  } = await supabase.auth.getUser();

  if (error || !user) {
    return null;
  }

  return user;
}

export const getViewer = cache(async (): Promise<Viewer | null> => {
  const authUser = await getSupabaseUser();
  if (!authUser) {
    return null;
  }

  const appUser = await ensureAppUserForAuthUser(authUser);
  return serializeViewer(appUser);
});

export async function requireViewer() {
  const viewer = await getViewer();
  if (!viewer || !viewer.is_active) {
    throw new Error("Authentication required.");
  }
  return viewer;
}

export async function loginWithCredentials(payload: {
  email: string;
  password: string;
}) {
  const email = normalizeEmail(payload.email);
  const password = payload.password;

  if (!email || !password) {
    throw new Error("Email and password are required.");
  }

  const supabase = await createSupabaseServerClient();
  const { data, error } = await supabase.auth.signInWithPassword({
    email,
    password,
  });

  if (error || !data.user) {
    throw new Error(
      translateAuthMessage(error?.message, "이메일 또는 비밀번호가 올바르지 않습니다."),
    );
  }

  const appUser = await touchAppUserLogin(data.user);
  return serializeViewer(appUser);
}

type SignupResult =
  | {
      requiresEmailConfirmation: true;
    }
  | {
      requiresEmailConfirmation: false;
      viewer: Viewer;
    };

export async function signupWithCredentials(payload: {
  email: string;
  password: string;
  username: string;
}): Promise<SignupResult> {
  await ensureAuthSchema();

  const email = normalizeEmail(payload.email);
  const password = payload.password;
  const username = validateUsername(payload.username);

  if (password.length < 8) {
    throw new Error("Password must be at least 8 characters long.");
  }

  const usernameRows = await sql<{ id: number }[]>`
    select id
    from users
    where username = ${username}
    limit 1
  `;
  if (usernameRows.length > 0) {
    throw new Error("Username already exists.");
  }

  const emailRows = await sql<{ id: number }[]>`
    select id
    from users
    where email = ${email}
    limit 1
  `;
  if (emailRows.length > 0) {
    throw new Error("Email already exists.");
  }

  const supabase = await createSupabaseServerClient();
  const { data, error } = await supabase.auth.signUp({
    email,
    password,
    options: {
      data: {
        username,
      },
      emailRedirectTo: getSiteUrl(),
    },
  });

  if (error) {
    throw new Error(translateAuthMessage(error.message, "회원가입에 실패했습니다."));
  }

  if (!data.user) {
    throw new Error(
      "이미 사용 중이거나 확인 대기 중인 이메일일 수 있습니다. 다른 이메일을 사용하거나 확인 메일을 먼저 확인해 주세요.",
    );
  }

  if (!data.session) {
    return {
      requiresEmailConfirmation: true,
    };
  }

  const appUser = await touchAppUserLogin(data.user);
  return {
    requiresEmailConfirmation: false,
    viewer: serializeViewer(appUser),
  };
}
